/* eslint-disable */
// Generated by Wrangler by running `wrangler types worker-configuration.d.ts --include-env=true --include-runtime=false` (hash: 4ba36d654ac6a52fcdda4c2c4e6d64de)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env {
		IMAGE_KV: KVNamespace;
		IMAGES_BUCKET: R2Bucket;
		LIST_KEY: "image_lists.json";
		BASE_URL: "";
	}
}
interface Env extends Cloudflare.Env {}
